When runs fail, save and report run failure to Slack (#729)
* WIP add failures to artifacts

* Try only uploading on failure

* Upload artifact

* Attempt to add logs from run failures into the Slack message

* remove file from another branch

* Update slack notifs for failures

* Use code block instead of text

* Convert size diffs to MB and round

* WIP fix validation errors, use tee

* Capture non-zero exit codes with tee

* WIP debug problem with empty log files for validation failures

* Fix tee logging

* Format failure as code block

* Respond to review comments

* Fix url handling

* Try new strategy for logging errors to Slack

* Fix failure

* If too long, concatenate unchanged block texts

* WIP test gha issue creation

* Oops, make slack announcement last item

* Oops, more conditionals

* try reconstructing bash

* Try to fix github URL

* Fix script name

* Try with more explicit env vars

* Test check how GH output is set

* Try fixing quoting

* Fix code rendering

* Try with markdown table rendering

* Try with markdown table rendering

* Oh wow, add pandas for the first time!

* Seperate out workflow for GH and slack, trim Slack limit, drop cron conditions for GHA

* Update error files to handle no file case, point slack at error messages

* Try to address double inclusion of validation failures

* Fix var assignment in Slack script

* Fix outdated template note

* Fix failure condition

* Drop early release checker template, copy pattern over there

* Respond to review comments

diff --git a/.github/workflows/run-archiver.yml b/.github/workflows/run-archiver.yml
--- a/.github/workflows/run-archiver.yml
+++ b/.github/workflows/run-archiver.yml
@@ -53,6 +53,8 @@ jobs:
 
       - name: Set up pixi
         uses: prefix-dev/setup-pixi@v0.8.14
+        with:
+          cache: true
 
       - name: Log the pixi environment
         run: |
@@ -72,7 +74,7 @@ jobs:
           ZENODO_TOKEN_PUBLISH: ${{ secrets.ZENODO_TOKEN_PUBLISH }}
         if: ${{inputs.server == 'production' || github.event_name == 'schedule'}}
         run: |
-          pixi run pudl_archiver --datasets ${{ matrix.dataset }} --summary-file ${{ matrix.dataset }}_run_summary.json --clobber-unchanged
+          pixi run pudl_archiver --datasets ${{ matrix.dataset }} --summary-file ${{ matrix.dataset }}_run_summary.json --clobber-unchanged 2>&1 | tee ${{ matrix.dataset }}_log.txt
 
       - name: Run sandbox archiver for ${{ matrix.dataset }}
         env:
@@ -82,8 +84,18 @@ jobs:
           ZENODO_TOKEN_UPLOAD: ${{ secrets.ZENODO_TOKEN_UPLOAD }}
           ZENODO_TOKEN_PUBLISH: ${{ secrets.ZENODO_TOKEN_PUBLISH }}
         if: ${{ inputs.server == 'sandbox' }}
+        # set -o pipefail passes on any failure codes to the next step,
+        # enabling us to see whether or not the pudl_archiver run failed.
         run: |
-          pixi run pudl_archiver --datasets ${{ matrix.dataset }} --sandbox --summary-file ${{ matrix.dataset }}_run_summary.json --clobber-unchanged
+          set -o pipefail
+          pixi run pudl_archiver --datasets ${{ matrix.dataset }} --sandbox --summary-file ${{ matrix.dataset }}_run_summary.json --clobber-unchanged 2>&1 | tee ${{ matrix.dataset }}_log.txt
+
+      - name: Save failed runs
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: error-log-${{ matrix.dataset }}
+          path: ${{ matrix.dataset }}_log.txt
 
       - name: Upload run summaries
         if: always()
@@ -101,45 +113,107 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Download summaries
-        id: download
+        id: download-summaries
         uses: actions/download-artifact@v4
         with:
           pattern: run-summaries-*
           merge-multiple: true
-      - name: show summaries
+      - name: Download failures
+        id: download-artifacts
+        uses: actions/download-artifact@v4
+        with:
+          pattern: error-log-*
+          merge-multiple: true
+      - name: Show downloaded artifacts
         run: ls -R
-      - name: Munge summaries together
-        id: all_summaries
+      # These steps only run to create a Github issue summarizing the run.
+      - name: Load pixi from cache
+        if: ${{ always() && (github.event_name == 'schedule' || inputs.create_github_issue == true) }}
+        uses: prefix-dev/setup-pixi@v0.8.13
+      - name: Munge summaries together for Github
+        if: ${{ always() && (github.event_name == 'schedule' || inputs.create_github_issue == true) }}
+        id: github_summaries
+        run: |
+          {
+            echo 'ERRORS<<DELIM1'
+            pixi run ./scripts/make_github_notification.py --summary-files *_run_summary.json --error-files *_log.txt --summary-type error
+            echo 'DELIM1'
+            echo 'FAILURES<<DELIM2'
+            pixi run ./scripts/make_github_notification.py --summary-files *_run_summary.json --error-files *_log.txt --summary-type failure
+            echo 'DELIM2'
+            echo 'CHANGES<<DELIM3'
+            pixi run ./scripts/make_github_notification.py --summary-files *_run_summary.json --error-files *_log.txt --summary-type change
+            echo 'DELIM3'
+            echo 'UNCHANGED<<DELIM4'
+            pixi run ./scripts/make_github_notification.py --summary-files *_run_summary.json --error-files *_log.txt --summary-type unchanged
+            echo 'DELIM4'
+          } | tee -a $GITHUB_OUTPUT
+      # These steps only run if no Github issue is requested to be created.
+      # The summary will show up in Slack instead.
+      - name: Munge summaries for Slack
+        id: slack_summaries
+        if: ${{ inputs.create_github_issue == false }}
         run: |
           {
             echo "SLACK_PAYLOAD<<EOF"
-            ./scripts/make_slack_notification_message.py --summary-files *_run_summary.json | tee slack-payload.json
+            ./scripts/make_slack_notification_message.py --summary-files *_run_summary.json --error-files *_log.txt | tee slack-payload.json
             echo "EOF"
           } >> "$GITHUB_OUTPUT"
       - name: Post update to pudl-deployment
+        if: ${{ inputs.create_github_issue == false }}
         uses: slackapi/slack-github-action@v2.1.1
         with:
           method: chat.postMessage
           token: ${{ secrets.PUDL_DEPLOY_SLACK_TOKEN }}
           payload: |
             text: "PUDL data archive run complete."
-            blocks: ${{ steps.all_summaries.outputs.SLACK_PAYLOAD }}
+            blocks: ${{ steps.slack_summaries.outputs.SLACK_PAYLOAD }}
             channel: "C03FHB9N0PQ"
 
+    outputs:
+      errors: ${{ steps.github_summaries.outputs.ERRORS }}
+      failures: ${{ steps.github_summaries.outputs.FAILURES }}
+      changes: ${{ steps.github_summaries.outputs.CHANGES }}
+      unchanged: ${{ steps.github_summaries.outputs.UNCHANGED }}
+
   make-github-issue:
-    # If event is a scheduled run on the first of the month or a workflow run where an issue
-    # is requested, create an issue. Do not create issues for weekly Monday runs to avoid
-    # having to manually close them for now, given the goal of publishing archives monthly.
-    if: ${{ always() && ((github.event_name == 'schedule' && github.event.schedule == '21 8 1 * *') || inputs.create_github_issue == true) }}
+    # If event is a scheduled run or a workflow run where an issue
+    # is requested, create an issue.
+    if: ${{ always() && (github.event_name == 'schedule' || inputs.create_github_issue == true) }}
     runs-on: ubuntu-latest
     needs:
       - archive-run
+      - archive-notify
     steps:
       - uses: actions/checkout@v4
       - name: Create an issue
+        id: create-issue
         uses: JasonEtco/create-an-issue@v2.9.2
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+          ERRORS: ${{ needs.archive-notify.outputs.errors }}
+          FAILURES: ${{ needs.archive-notify.outputs.failures }}
+          CHANGES: ${{ needs.archive-notify.outputs.changes }}
+          UNCHANGED: ${{ needs.archive-notify.outputs.unchanged }}
         with:
           filename: .github/ISSUE_TEMPLATE/monthly-archive-update.md
+      - run: echo "URL=${{ steps.create-issue.outputs.url }}" >> $GITHUB_ENV
+    outputs:
+      url: ${{ steps.create-issue.outputs.URL}}
+
+  make-slack-announcement-for-github-issue:
+    runs-on: ubuntu-latest
+    needs:
+      - archive-run
+      - make-github-issue
+    env:
+      github-url: ${{ needs.make-github-issue.outputs.url }}
+    steps:
+      - uses: slackapi/slack-github-action@v2.1.1
+        with:
+          method: chat.postMessage
+          token: ${{ secrets.PUDL_DEPLOY_SLACK_TOKEN }}
+          payload: |
+            text: "PUDL data archive run complete: ${{ env.github-url }}"
+            channel: "C03FHB9N0PQ"
